### ISSUE TITLE
Format/Clean Up "About" page

### ISSUE THREAD

**Issue by dylviz** [IndexerDAO/webApp#4]
The about page is mostly just text. Haven't put any time in designing

**Comment by alex-pakalniskis** [comment]
I think it would be valuable to add (at least some of) the following information to this page (either as lists or tables, I don't really have a strong preference):
* amount of grant funding we've received for our projects
  * i.e. The Graph Community Grant for Indexing 101, 68027.21 GRT
* amount of GRT we've staked in The Graph protocol
  * pull from subgraph query
* our current subgraph allocations
   * pull from subgraph query 
* amount of GRT income we've earned
  * pull from subgraph query
* amount of GRT rewards we've earned in MIPs
  * copy from wherever it's posted lol

**Comment by dylviz** [comment]
https://github.com/IndexerDAO/webApp/pull/17

**Comment by reinasun** [comment]
I really like the idea of adding this. Should it be on the about us page? or home page?
